### ISSUE TITLE
Voyager as admin package

### ISSUE THREAD

**Issue by evelicanin** [laravel-factory/feature-requests#4]
Voyager is my preffered back end option, 
Any chance you might have Voyager as an admin option?

**Comment by gauravmak** [comment]
We will surely consider the possibilities @evelicanin 
Thanks.

**Comment by gauravmak** [comment]
@evelicanin 
We have done our research and it will not be possible to provide Voyager as an admin option.

Actually, Voyager is a complete rather than just an admin panel theme.

Rather than good option will be to work on Voyager features that are useful to you and other users.
Authorization part is already on our list. You may let us know your other favorite features from Voyager. Thanks.
